### ISSUE TITLE
Little bug in connect_mqtt (line 116 server.py)

### ISSUE THREAD

**Issue by nathanp512** [rootje/hoymiles-mqtt#2]
Thank you for your great work!
I just found a little bug in line 116 in server.py. The third argument should be MQTT_USERNAME instead of MQTT_PASSWORD.

Suggestion: 
client = connect_mqtt(MQTT_HOST_ADDRESS, MQTT_PORT, MQTT_USERNAME, MQTT_PASSWORD)

Kind regards, Nathan

**Comment by rootje** [comment]
Hi Nathan,

Thank you for your message! You are absolutely right. I will make the change and do the commit.

Greetz, Roland

**Comment by rootje** [comment]
@nathanp512  I've implemented a docker pipeline and updated some frameworks and docker base images as well. So if you're using the docker image you might want to upgrade.

**Comment by nathanp512** [comment]
Thanks @rootje ! The updated Docker image works perfectly!
